options:
  kafka-release-channel:
    type: string
    default: stable
    description: The release channel of the kafka snap package. This will be ignored if the snap file is attached as a resource or built with the charm.